version: '3.5'

services:
  inatel_db:  # Service, server
    image: postgres
    environment:
      POSTGRES_PASSWORD: root  # DB password
      POSTGRES_DB: inatel  # DB Name, not the username
    ports:
      - "5433:5432"
    volumes:
      - /backup/files:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  postgres-data:
