# Generated by Django 4.2.5 on 2023-10-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='is_capital',
            field=models.BooleanField(default=False),
        ),
    ]
