# Generated by Django 4.2.5 on 2023-10-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.country'),
        ),
    ]
