# Generated by Django 4.2.5 on 2023-10-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cidade_state_state_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
