# Generated by Django 4.2.5 on 2023-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_cidade_options_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
