# Generated by Django 4.2.5 on 2023-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_cidade_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
